# Generated by Django 5.1.2 on 2024-10-30 11:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=5000)),
                ('description', models.TextField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country_description', models.TextField(blank=True, max_length=5000)),
                ('capital', models.TextField(blank=True, max_length=255)),
                ('area', models.TextField(blank=True, max_length=255)),
                ('population', models.TextField(blank=True, max_length=255)),
                ('language', models.TextField(blank=True, max_length=255)),
                ('currency', models.TextField(blank=True, max_length=255)),
                ('government', models.TextField(blank=True, max_length=255)),
                ('regions', models.TextField(blank=True, max_length=255)),
                ('climate', models.TextField(blank=True, max_length=255)),
                ('major_industries', models.TextField(blank=True, max_length=255)),
                ('cultural_heritage', models.TextField(blank=True, max_length=255)),
                ('natural_features', models.TextField(blank=True, max_length=255)),
                ('membership', models.TextField(blank=True, max_length=255)),
                ('country_image', models.ImageField(blank=True, upload_to='photos/countries')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('service_image', models.ImageField(upload_to='photos/services')),
                ('title2', models.CharField(max_length=50, unique=True)),
                ('description2', models.TextField(max_length=5000)),
                ('highlight1', models.TextField(max_length=5000)),
                ('highlight2', models.TextField(max_length=5000)),
                ('highlight3', models.TextField(max_length=5000)),
                ('highlight4', models.TextField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='photos/testimonials')),
                ('video_url', models.URLField()),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='CountryFaq',
            fields=[
                ('cfaq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=5000)),
                ('answer', models.TextField(max_length=5000)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.country')),
            ],
            options={
                'verbose_name': 'CountryFaq',
                'verbose_name_plural': 'CountryFaq(s)',
            },
        ),
        migrations.CreateModel(
            name='ServiceFaq',
            fields=[
                ('sfaq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=5000)),
                ('answer', models.TextField(max_length=5000)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.service')),
            ],
            options={
                'verbose_name': 'ServiceFaq',
                'verbose_name_plural': 'ServiceFaq(s)',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='photos/vacancies')),
                ('description', models.TextField(max_length=5000)),
                ('service_fee', models.CharField(default='0', max_length=50)),
                ('salary', models.CharField(default='0', max_length=10)),
                ('food', models.CharField(default='0', max_length=50)),
                ('accomodation', models.CharField(default='0', max_length=50)),
                ('processing_time', models.CharField(default='0', max_length=50)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 16, 50, 44, 425600))),
                ('last_date', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.country')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
