# Generated by Django 5.1.2 on 2024-10-30 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryfaq',
            old_name='cfaq_id',
            new_name='cfaqid',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_id',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='servicefaq',
            old_name='sfaq_id',
            new_name='sfaqid',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_id',
            new_name='vid',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 17, 12, 41, 976606)),
        ),
    ]
