# Generated by Django 5.1.2 on 2024-10-31 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_cfaq_id_countryfaq_cfaqid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_id',
            new_name='cid',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 31, 11, 7, 29, 954369)),
        ),
    ]
