# Generated by Django 5.1.2 on 2024-10-31 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_country_id_country_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 31, 18, 53, 1, 474358)),
        ),
    ]
